/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2025-03-27 11:39:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.interactive;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fincludeParams_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fnamespace_005fincludeParams_005faction_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsx_005fhead_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsx_005fbind_0026_005ftargets_005flistenTopics_005fid_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsx_005ftabbedpanel_0026_005fid_005fcssClass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsx_005fdiv_0026_005flabel_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ftextarea_0026_005ftheme_005fname_005fcssClass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsx_005fsubmit_0026_005fvalue_005ftargets_005flistenTopics_005fhref_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsx_005fdiv_0026_005flistenTopics_005fid_005fcssClass;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fincludeParams_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fnamespace_005fincludeParams_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsx_005fhead_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsx_005fbind_0026_005ftargets_005flistenTopics_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsx_005ftabbedpanel_0026_005fid_005fcssClass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsx_005fdiv_0026_005flabel_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005ftextarea_0026_005ftheme_005fname_005fcssClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsx_005fsubmit_0026_005fvalue_005ftargets_005flistenTopics_005fhref_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsx_005fdiv_0026_005flistenTopics_005fid_005fcssClass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fincludeParams_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fnamespace_005fincludeParams_005faction_005fnobody.release();
    _005fjspx_005ftagPool_005fsx_005fhead_005fnobody.release();
    _005fjspx_005ftagPool_005fsx_005fbind_0026_005ftargets_005flistenTopics_005fid_005fnobody.release();
    _005fjspx_005ftagPool_005fsx_005ftabbedpanel_0026_005fid_005fcssClass.release();
    _005fjspx_005ftagPool_005fsx_005fdiv_0026_005flabel_005fid.release();
    _005fjspx_005ftagPool_005fs_005ftextarea_0026_005ftheme_005fname_005fcssClass_005fnobody.release();
    _005fjspx_005ftagPool_005fsx_005fsubmit_0026_005fvalue_005ftargets_005flistenTopics_005fhref_005fnobody.release();
    _005fjspx_005ftagPool_005fsx_005fdiv_0026_005flistenTopics_005fid_005fcssClass.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>OGNL and tags demo</title>\n");
      out.write("    ");
      if (_jspx_meth_s_005furl_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_s_005furl_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_s_005furl_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_s_005furl_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_s_005furl_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    \n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${struts}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/webconsole.js\"></script>\n");
      out.write("    ");
      if (_jspx_meth_sx_005fhead_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    <script>\n");
      out.write("        var index = -1;\n");
      out.write("        var runningOgnl = true;\n");
      out.write("        var ognlBase = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ognlBase}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\n");
      out.write("        var jspBase = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jspBase}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\n");
      out.write("        var ognlCount = 9;\n");
      out.write("        var jspCount = 5;\n");
      out.write("        \n");
      out.write("        dojo.addOnLoad(function() {\n");
      out.write("            var classSrc = dojo.byId(\"classSrc\");\n");
      out.write("            dojo.io.updateNode(classSrc, \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${viewClass}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\");\n");
      out.write("            dojo.html.hide(\"previous\");\n");
      out.write("            dojo.html.hide(\"next\");\n");
      out.write("        });\n");
      out.write("        \n");
      out.write("        dojo.event.topic.subscribe(\"/reloadGuide\", function() {\n");
      out.write("            next();\n");
      out.write("        });\n");
      out.write("        \n");
      out.write("        function startOgnl() {\n");
      out.write("            selectOGNLTab();\n");
      out.write("            index = -1;\n");
      out.write("            runningOgnl = true;\n");
      out.write("            change(1);\n");
      out.write("            updateNavigation();\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function startJSP() {\n");
      out.write("            selectJSPTab();\n");
      out.write("            index = -1;\n");
      out.write("            runningOgnl = false;\n");
      out.write("            change(1);\n");
      out.write("            updateNavigation();\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function execOgnl(id) {\n");
      out.write("            var exp = dojo.string.trim(dojo.byId(id ? id : \"example\").innerHTML);\n");
      out.write("            dojo.byId(\"wc-command\").value = exp;\n");
      out.write("            \n");
      out.write("            keyEvent({keyCode : 13}, '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jspEval}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function execJSP(id) {\n");
      out.write("            var exp = dojo.string.trim(dojo.byId(id ? id : \"example\").innerHTML);\n");
      out.write("            dojo.byId(\"jsp\").value = unscape(exp);\n");
      out.write("            \n");
      out.write("            dojo.event.topic.publish(\"/evalJSP\")\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function unscape(str) {\n");
      out.write("            return str.replace(/&amp;/gm, \"&\").replace(/&lt;/gm, \"<\").replace(/&gt;/gm, \">\").replace(/&quot;/gm, '\"');\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function selectClassSrcTab() {\n");
      out.write("            dojo.widget.byId(\"mainTabContainer\").selectTab(\"classTab\");\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function selectJSPTab() {\n");
      out.write("            dojo.widget.byId(\"mainTabContainer\").selectTab(\"jspTab\");\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function selectOGNLTab() {\n");
      out.write("            dojo.widget.byId(\"mainTabContainer\").selectTab(\"ognlTab\");\n");
      out.write("        }\n");
      out.write("       \n");
      out.write("        function change(delta) {\n");
      out.write("            index+=delta;\n");
      out.write("            \n");
      out.write("            var url = (runningOgnl ? ognlBase : jspBase) + index + \".jsp\";\n");
      out.write("            var bind = dojo.widget.byId(\"guideBind\");\n");
      out.write("            bind.href = url;\n");
      out.write("            dojo.event.topic.publish(\"/loadContent\");\n");
      out.write("            updateNavigation();\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function updateNavigation() {\n");
      out.write("            if(index <= 0) {\n");
      out.write("                dojo.html.hide(\"previous\");\n");
      out.write("            } else {\n");
      out.write("                dojo.html.show(\"previous\");\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            var top = runningOgnl ? ognlCount : jspCount;\n");
      out.write("            \n");
      out.write("            if(index == top - 1) {\n");
      out.write("                dojo.html.hide(\"next\");\n");
      out.write("            } else {\n");
      out.write("                dojo.html.show(\"next\");\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    \n");
      out.write("    <style type=\"\">\n");
      out.write("        .wc-results {\n");
      out.write("            overflow: auto; \n");
      out.write("            margin: 0px; \n");
      out.write("            padding: 5px; \n");
      out.write("            font-family: courier; \n");
      out.write("            color: white; \n");
      out.write("            background-color: black; \n");
      out.write("            height: 200px;\n");
      out.write("        }\n");
      out.write("        .wc-results pre {\n");
      out.write("            display: inline;\n");
      out.write("        }\n");
      out.write("        .wc-command {\n");
      out.write("            margin: 1px 0 0 0; \n");
      out.write("        }\n");
      out.write("        .shell {\n");
      out.write("            width: 100%;\n");
      out.write("        }\n");
      out.write("       \n");
      out.write("        .jsp {\n");
      out.write("            border-style: solid;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 200px;\n");
      out.write("        }\n");
      out.write("        .jspResult {\n");
      out.write("            border-style: none;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 200px;\n");
      out.write("            padding: 5px;\n");
      out.write("        }\n");
      out.write("        .jspResultHeader {\n");
      out.write("            background-color: #818EBD;\n");
      out.write("            color: white;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 15px;\n");
      out.write("        }\n");
      out.write("        .jspResultHeader span {\n");
      out.write("            padding: 5px;\n");
      out.write("        }\n");
      out.write("        .classSrc {\n");
      out.write("            font-family:Courier;\n");
      out.write("            font-size:11px;\n");
      out.write("            line-height:13px;\n");
      out.write("            overflow: auto; \n");
      out.write("            height: 400px;\n");
      out.write("            width: 100%;\n");
      out.write("        }\n");
      out.write("        .tabContainer {\n");
      out.write("            width: 1000px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("        }\n");
      out.write("        .guideContainer {\n");
      out.write("            width: 600px;\n");
      out.write("            border-width: 1px;\n");
      out.write("            border-style: solid;\n");
      out.write("            margin: 0 auto;\n");
      out.write("        }\n");
      out.write("        .guide {\n");
      out.write("            padding: 5px;\n");
      out.write("        }\n");
      out.write("        pre {\n");
      out.write("            font-family:Verdana,Geneva,Arial,Helvetica,sans-serif;\n");
      out.write("            font-style: italic;\n");
      out.write("        }\n");
      out.write("        span.kw {\n");
      out.write("            color: rgb(127, 0, 85);\n");
      out.write("            font-weight: bold;;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("\n");
      if (_jspx_meth_sx_005fbind_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    ");
      if (_jspx_meth_sx_005ftabbedpanel_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    <br/><br/>\n");
      out.write("    <div class=\"guideContainer\">\n");
      out.write("        <div class=\"jspResultHeader\">\n");
      out.write("            <span>Interactive Guide</span>\n");
      out.write("        </div>\n");
      out.write("        ");
      if (_jspx_meth_sx_005fdiv_005f3(_jspx_page_context))
        return;
      out.write("   \n");
      out.write("        <div>\n");
      out.write("            <a href=\"#\" id=\"previous\" onclick=\"change(-1)\" style=\"float: left\"><< Previous</a>\n");
      out.write("            <a href=\"#\" id=\"next\" onclick=\"change(1)\" style=\"float: right\">Next >></a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f0 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fincludeParams_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    boolean _jspx_th_s_005furl_005f0_reused = false;
    try {
      _jspx_th_s_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005furl_005f0.setParent(null);
      // /interactive/index.jsp(8,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005furl_005f0.setVar("struts");
      // /interactive/index.jsp(8,4) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005furl_005f0.setValue("/struts");
      // /interactive/index.jsp(8,4) name = includeParams type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005furl_005f0.setIncludeParams("none");
      int _jspx_eval_s_005furl_005f0 = _jspx_th_s_005furl_005f0.doStartTag();
      if (_jspx_th_s_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fincludeParams_005fnobody.reuse(_jspx_th_s_005furl_005f0);
      _jspx_th_s_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_s_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f1 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fnamespace_005fincludeParams_005faction_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    boolean _jspx_th_s_005furl_005f1_reused = false;
    try {
      _jspx_th_s_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005furl_005f1.setParent(null);
      // /interactive/index.jsp(9,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005furl_005f1.setVar("jspEval");
      // /interactive/index.jsp(9,4) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005furl_005f1.setAction("jspEval");
      // /interactive/index.jsp(9,4) name = namespace type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005furl_005f1.setNamespace("/nodecorate");
      // /interactive/index.jsp(9,4) name = includeParams type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005furl_005f1.setIncludeParams("none");
      int _jspx_eval_s_005furl_005f1 = _jspx_th_s_005furl_005f1.doStartTag();
      if (_jspx_th_s_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fnamespace_005fincludeParams_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f1);
      _jspx_th_s_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_s_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f2 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fincludeParams_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    boolean _jspx_th_s_005furl_005f2_reused = false;
    try {
      _jspx_th_s_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_s_005furl_005f2.setParent(null);
      // /interactive/index.jsp(10,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005furl_005f2.setVar("viewClass");
      // /interactive/index.jsp(10,4) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005furl_005f2.setValue("/interactive/example-action.jsp");
      // /interactive/index.jsp(10,4) name = includeParams type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005furl_005f2.setIncludeParams("none");
      int _jspx_eval_s_005furl_005f2 = _jspx_th_s_005furl_005f2.doStartTag();
      if (_jspx_th_s_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fincludeParams_005fnobody.reuse(_jspx_th_s_005furl_005f2);
      _jspx_th_s_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_s_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f3 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fincludeParams_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    boolean _jspx_th_s_005furl_005f3_reused = false;
    try {
      _jspx_th_s_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_s_005furl_005f3.setParent(null);
      // /interactive/index.jsp(11,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005furl_005f3.setVar("ognlBase");
      // /interactive/index.jsp(11,4) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005furl_005f3.setValue("/interactive/ognl_");
      // /interactive/index.jsp(11,4) name = includeParams type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005furl_005f3.setIncludeParams("none");
      int _jspx_eval_s_005furl_005f3 = _jspx_th_s_005furl_005f3.doStartTag();
      if (_jspx_th_s_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fincludeParams_005fnobody.reuse(_jspx_th_s_005furl_005f3);
      _jspx_th_s_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_s_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f4 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fincludeParams_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    boolean _jspx_th_s_005furl_005f4_reused = false;
    try {
      _jspx_th_s_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_s_005furl_005f4.setParent(null);
      // /interactive/index.jsp(12,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005furl_005f4.setVar("jspBase");
      // /interactive/index.jsp(12,4) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005furl_005f4.setValue("/interactive/jsp_");
      // /interactive/index.jsp(12,4) name = includeParams type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005furl_005f4.setIncludeParams("none");
      int _jspx_eval_s_005furl_005f4 = _jspx_th_s_005furl_005f4.doStartTag();
      if (_jspx_th_s_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005furl_0026_005fvar_005fvalue_005fincludeParams_005fnobody.reuse(_jspx_th_s_005furl_005f4);
      _jspx_th_s_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_s_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sx_005fhead_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sx:head
    org.apache.struts2.dojo.views.jsp.ui.HeadTag _jspx_th_sx_005fhead_005f0 = (org.apache.struts2.dojo.views.jsp.ui.HeadTag) _005fjspx_005ftagPool_005fsx_005fhead_005fnobody.get(org.apache.struts2.dojo.views.jsp.ui.HeadTag.class);
    boolean _jspx_th_sx_005fhead_005f0_reused = false;
    try {
      _jspx_th_sx_005fhead_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sx_005fhead_005f0.setParent(null);
      int _jspx_eval_sx_005fhead_005f0 = _jspx_th_sx_005fhead_005f0.doStartTag();
      if (_jspx_th_sx_005fhead_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsx_005fhead_005fnobody.reuse(_jspx_th_sx_005fhead_005f0);
      _jspx_th_sx_005fhead_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sx_005fhead_005f0, _jsp_getInstanceManager(), _jspx_th_sx_005fhead_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sx_005fbind_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sx:bind
    org.apache.struts2.dojo.views.jsp.ui.BindTag _jspx_th_sx_005fbind_005f0 = (org.apache.struts2.dojo.views.jsp.ui.BindTag) _005fjspx_005ftagPool_005fsx_005fbind_0026_005ftargets_005flistenTopics_005fid_005fnobody.get(org.apache.struts2.dojo.views.jsp.ui.BindTag.class);
    boolean _jspx_th_sx_005fbind_005f0_reused = false;
    try {
      _jspx_th_sx_005fbind_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sx_005fbind_005f0.setParent(null);
      // /interactive/index.jsp(180,0) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sx_005fbind_005f0.setId("guideBind");
      // /interactive/index.jsp(180,0) name = targets type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sx_005fbind_005f0.setTargets("guide");
      // /interactive/index.jsp(180,0) name = listenTopics type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sx_005fbind_005f0.setListenTopics("/loadContent");
      int _jspx_eval_sx_005fbind_005f0 = _jspx_th_sx_005fbind_005f0.doStartTag();
      if (_jspx_th_sx_005fbind_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsx_005fbind_0026_005ftargets_005flistenTopics_005fid_005fnobody.reuse(_jspx_th_sx_005fbind_005f0);
      _jspx_th_sx_005fbind_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sx_005fbind_005f0, _jsp_getInstanceManager(), _jspx_th_sx_005fbind_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sx_005ftabbedpanel_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sx:tabbedpanel
    org.apache.struts2.dojo.views.jsp.ui.TabbedPanelTag _jspx_th_sx_005ftabbedpanel_005f0 = (org.apache.struts2.dojo.views.jsp.ui.TabbedPanelTag) _005fjspx_005ftagPool_005fsx_005ftabbedpanel_0026_005fid_005fcssClass.get(org.apache.struts2.dojo.views.jsp.ui.TabbedPanelTag.class);
    boolean _jspx_th_sx_005ftabbedpanel_005f0_reused = false;
    try {
      _jspx_th_sx_005ftabbedpanel_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sx_005ftabbedpanel_005f0.setParent(null);
      // /interactive/index.jsp(183,4) name = id type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sx_005ftabbedpanel_005f0.setId("mainTabContainer");
      // /interactive/index.jsp(183,4) name = cssClass type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sx_005ftabbedpanel_005f0.setCssClass("tabContainer");
      int _jspx_eval_sx_005ftabbedpanel_005f0 = _jspx_th_sx_005ftabbedpanel_005f0.doStartTag();
      if (_jspx_eval_sx_005ftabbedpanel_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_sx_005ftabbedpanel_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_sx_005ftabbedpanel_005f0);
        }
        do {
          out.write("\n");
          out.write("        ");
          if (_jspx_meth_sx_005fdiv_005f0(_jspx_th_sx_005ftabbedpanel_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("        ");
          if (_jspx_meth_sx_005fdiv_005f1(_jspx_th_sx_005ftabbedpanel_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("        ");
          if (_jspx_meth_sx_005fdiv_005f2(_jspx_th_sx_005ftabbedpanel_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_sx_005ftabbedpanel_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_sx_005ftabbedpanel_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_sx_005ftabbedpanel_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsx_005ftabbedpanel_0026_005fid_005fcssClass.reuse(_jspx_th_sx_005ftabbedpanel_005f0);
      _jspx_th_sx_005ftabbedpanel_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sx_005ftabbedpanel_005f0, _jsp_getInstanceManager(), _jspx_th_sx_005ftabbedpanel_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sx_005fdiv_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sx_005ftabbedpanel_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sx:div
    org.apache.struts2.dojo.views.jsp.ui.DivTag _jspx_th_sx_005fdiv_005f0 = (org.apache.struts2.dojo.views.jsp.ui.DivTag) _005fjspx_005ftagPool_005fsx_005fdiv_0026_005flabel_005fid.get(org.apache.struts2.dojo.views.jsp.ui.DivTag.class);
    boolean _jspx_th_sx_005fdiv_005f0_reused = false;
    try {
      _jspx_th_sx_005fdiv_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sx_005fdiv_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sx_005ftabbedpanel_005f0);
      // /interactive/index.jsp(184,8) name = label type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sx_005fdiv_005f0.setLabel("OGNL Console");
      // /interactive/index.jsp(184,8) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sx_005fdiv_005f0.setId("ognlTab");
      int _jspx_eval_sx_005fdiv_005f0 = _jspx_th_sx_005fdiv_005f0.doStartTag();
      if (_jspx_eval_sx_005fdiv_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_sx_005fdiv_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_sx_005fdiv_005f0);
        }
        do {
          out.write("\n");
          out.write("            <div id=\"shell\" class=\"shell\">\n");
          out.write("               <form onsubmit=\"return false\" id=\"wc-form\">\n");
          out.write("                    <div class=\"wc-results\" id=\"wc-result\">\n");
          out.write("                         Welcome to the OGNL console!\n");
          out.write("                         <br />\n");
          out.write("                         :-&gt;\n");
          out.write("                    </div>\n");
          out.write("                    <input type=\"hidden\" name=\"debug\" value=\"command\" />\n");
          out.write("                    OGNL Expression <input name=\"expression\" onkeyup=\"keyEvent(event, '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jspEval}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("')\" class=\"input-xxlarge wc-command\" id=\"wc-command\" type=\"text\" />\n");
          out.write("                </form>\n");
          out.write("            </div>\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_sx_005fdiv_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_sx_005fdiv_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_sx_005fdiv_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsx_005fdiv_0026_005flabel_005fid.reuse(_jspx_th_sx_005fdiv_005f0);
      _jspx_th_sx_005fdiv_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sx_005fdiv_005f0, _jsp_getInstanceManager(), _jspx_th_sx_005fdiv_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sx_005fdiv_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_sx_005ftabbedpanel_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sx:div
    org.apache.struts2.dojo.views.jsp.ui.DivTag _jspx_th_sx_005fdiv_005f1 = (org.apache.struts2.dojo.views.jsp.ui.DivTag) _005fjspx_005ftagPool_005fsx_005fdiv_0026_005flabel_005fid.get(org.apache.struts2.dojo.views.jsp.ui.DivTag.class);
    boolean _jspx_th_sx_005fdiv_005f1_reused = false;
    try {
      _jspx_th_sx_005fdiv_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sx_005fdiv_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sx_005ftabbedpanel_005f0);
      // /interactive/index.jsp(197,8) name = label type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sx_005fdiv_005f1.setLabel("JSP Console");
      // /interactive/index.jsp(197,8) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sx_005fdiv_005f1.setId("jspTab");
      int _jspx_eval_sx_005fdiv_005f1 = _jspx_th_sx_005fdiv_005f1.doStartTag();
      if (_jspx_eval_sx_005fdiv_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_sx_005fdiv_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_sx_005fdiv_005f1);
        }
        do {
          out.write("\n");
          out.write("            <table style=\"width: 100%\" cellpadding=\"1\">\n");
          out.write("                <tr valign=\"top\">\n");
          out.write("                    <td width=\"50%\">\n");
          out.write("                       <form theme=\"simple\" namespace=\"/nodecorate\" action=\"jspEval\" method=\"post\">\n");
          out.write("                           ");
          if (_jspx_meth_s_005ftextarea_005f0(_jspx_th_sx_005fdiv_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                           ");
          if (_jspx_meth_sx_005fsubmit_005f0(_jspx_th_sx_005fdiv_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                       </form>\n");
          out.write("                    </td>\n");
          out.write("                    <td width=\"50%\">\n");
          out.write("                        <div class=\"jspResultHeader\">\n");
          out.write("                            <span>JSP Eval Result</span>\n");
          out.write("                        </div>\n");
          out.write("                        <div id=\"jspResult\" class=\"jspResult\">\n");
          out.write("                        </div>\n");
          out.write("                    </td>\n");
          out.write("                </tr>\n");
          out.write("            </table>    \n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_sx_005fdiv_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_sx_005fdiv_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_sx_005fdiv_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsx_005fdiv_0026_005flabel_005fid.reuse(_jspx_th_sx_005fdiv_005f1);
      _jspx_th_sx_005fdiv_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sx_005fdiv_005f1, _jsp_getInstanceManager(), _jspx_th_sx_005fdiv_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ftextarea_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sx_005fdiv_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:textarea
    org.apache.struts2.views.jsp.ui.TextareaTag _jspx_th_s_005ftextarea_005f0 = (org.apache.struts2.views.jsp.ui.TextareaTag) _005fjspx_005ftagPool_005fs_005ftextarea_0026_005ftheme_005fname_005fcssClass_005fnobody.get(org.apache.struts2.views.jsp.ui.TextareaTag.class);
    boolean _jspx_th_s_005ftextarea_005f0_reused = false;
    try {
      _jspx_th_s_005ftextarea_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005ftextarea_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sx_005fdiv_005f1);
      // /interactive/index.jsp(202,27) name = cssClass type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftextarea_005f0.setCssClass("jsp");
      // /interactive/index.jsp(202,27) name = theme type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftextarea_005f0.setTheme("simple");
      // /interactive/index.jsp(202,27) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ftextarea_005f0.setName("jsp");
      int _jspx_eval_s_005ftextarea_005f0 = _jspx_th_s_005ftextarea_005f0.doStartTag();
      if (_jspx_th_s_005ftextarea_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005ftextarea_0026_005ftheme_005fname_005fcssClass_005fnobody.reuse(_jspx_th_s_005ftextarea_005f0);
      _jspx_th_s_005ftextarea_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005ftextarea_005f0, _jsp_getInstanceManager(), _jspx_th_s_005ftextarea_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sx_005fsubmit_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sx_005fdiv_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sx:submit
    org.apache.struts2.dojo.views.jsp.ui.SubmitTag _jspx_th_sx_005fsubmit_005f0 = (org.apache.struts2.dojo.views.jsp.ui.SubmitTag) _005fjspx_005ftagPool_005fsx_005fsubmit_0026_005fvalue_005ftargets_005flistenTopics_005fhref_005fnobody.get(org.apache.struts2.dojo.views.jsp.ui.SubmitTag.class);
    boolean _jspx_th_sx_005fsubmit_005f0_reused = false;
    try {
      _jspx_th_sx_005fsubmit_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sx_005fsubmit_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sx_005fdiv_005f1);
      // /interactive/index.jsp(203,27) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sx_005fsubmit_005f0.setValue("Eval JSP Fragment");
      // /interactive/index.jsp(203,27) name = href type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sx_005fsubmit_005f0.setHref("%{#jspEval}");
      // /interactive/index.jsp(203,27) name = targets type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sx_005fsubmit_005f0.setTargets("jspResult");
      // /interactive/index.jsp(203,27) name = listenTopics type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sx_005fsubmit_005f0.setListenTopics("/evalJSP");
      int _jspx_eval_sx_005fsubmit_005f0 = _jspx_th_sx_005fsubmit_005f0.doStartTag();
      if (_jspx_th_sx_005fsubmit_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsx_005fsubmit_0026_005fvalue_005ftargets_005flistenTopics_005fhref_005fnobody.reuse(_jspx_th_sx_005fsubmit_005f0);
      _jspx_th_sx_005fsubmit_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sx_005fsubmit_005f0, _jsp_getInstanceManager(), _jspx_th_sx_005fsubmit_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sx_005fdiv_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_sx_005ftabbedpanel_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sx:div
    org.apache.struts2.dojo.views.jsp.ui.DivTag _jspx_th_sx_005fdiv_005f2 = (org.apache.struts2.dojo.views.jsp.ui.DivTag) _005fjspx_005ftagPool_005fsx_005fdiv_0026_005flabel_005fid.get(org.apache.struts2.dojo.views.jsp.ui.DivTag.class);
    boolean _jspx_th_sx_005fdiv_005f2_reused = false;
    try {
      _jspx_th_sx_005fdiv_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sx_005fdiv_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sx_005ftabbedpanel_005f0);
      // /interactive/index.jsp(220,8) name = label type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sx_005fdiv_005f2.setLabel("Class on top of the Value Stack");
      // /interactive/index.jsp(220,8) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sx_005fdiv_005f2.setId("classTab");
      int _jspx_eval_sx_005fdiv_005f2 = _jspx_th_sx_005fdiv_005f2.doStartTag();
      if (_jspx_eval_sx_005fdiv_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_sx_005fdiv_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_sx_005fdiv_005f2);
        }
        do {
          out.write("\n");
          out.write("            <div id=\"classSrc\" class=\"classSrc\">\n");
          out.write("            </div>\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_sx_005fdiv_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_sx_005fdiv_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_sx_005fdiv_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsx_005fdiv_0026_005flabel_005fid.reuse(_jspx_th_sx_005fdiv_005f2);
      _jspx_th_sx_005fdiv_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sx_005fdiv_005f2, _jsp_getInstanceManager(), _jspx_th_sx_005fdiv_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sx_005fdiv_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sx:div
    org.apache.struts2.dojo.views.jsp.ui.DivTag _jspx_th_sx_005fdiv_005f3 = (org.apache.struts2.dojo.views.jsp.ui.DivTag) _005fjspx_005ftagPool_005fsx_005fdiv_0026_005flistenTopics_005fid_005fcssClass.get(org.apache.struts2.dojo.views.jsp.ui.DivTag.class);
    boolean _jspx_th_sx_005fdiv_005f3_reused = false;
    try {
      _jspx_th_sx_005fdiv_005f3.setPageContext(_jspx_page_context);
      _jspx_th_sx_005fdiv_005f3.setParent(null);
      // /interactive/index.jsp(230,8) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sx_005fdiv_005f3.setId("guide");
      // /interactive/index.jsp(230,8) name = listenTopics type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sx_005fdiv_005f3.setListenTopics("/reloadGuide");
      // /interactive/index.jsp(230,8) name = cssClass type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sx_005fdiv_005f3.setCssClass("guide");
      int _jspx_eval_sx_005fdiv_005f3 = _jspx_th_sx_005fdiv_005f3.doStartTag();
      if (_jspx_eval_sx_005fdiv_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_sx_005fdiv_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_sx_005fdiv_005f3);
        }
        do {
          out.write("\n");
          out.write("            <p><a href=\"#\" onclick=\"startOgnl()\">Start OGNL Interactive Demo</a></p>\n");
          out.write("            <p><a href=\"#\" onclick=\"startJSP()\">Start JSP Interactive Demo</a></p>\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_sx_005fdiv_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_sx_005fdiv_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_sx_005fdiv_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsx_005fdiv_0026_005flistenTopics_005fid_005fcssClass.reuse(_jspx_th_sx_005fdiv_005f3);
      _jspx_th_sx_005fdiv_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sx_005fdiv_005f3, _jsp_getInstanceManager(), _jspx_th_sx_005fdiv_005f3_reused);
    }
    return false;
  }
}
